### ISSUE TITLE
speed graph won't show in Firefox

### ISSUE THREAD

**Issue by tomByrer** [marko-js/website#15]
Hovering other view libs works, but not the gray bars in Firefox Nightly 55, but works in Chrome.
TIA!

![markojs com-bug-firefox](https://user-images.githubusercontent.com/1308419/27003848-12ac58b6-4dc4-11e7-917c-922704e14802.png)

**Comment by austinkelleher** [comment]
I just tried this on Firefox Nightly `55.0a1 (2017-06-12) (64-bit)` and I am seeing the gray bars. Can you try again and see if this is still an issue? It may be a browser issue that has now been fixed.

**Comment by austinkelleher** [comment]
@tomByrer I'm not seeing this on OS X. What OS are you using? I assume that this is not an issue with our website, but rather an issue with Firefox Nightly on your OS.

**Comment by DylanPiercey** [comment]
No info for a while and also haven't been a able to replicate the issue. Closing for now.
