### ISSUE TITLE
`undefined` should be mentioned re conditional attributes

### ISSUE THREAD

**Issue by tjcrowder** [marko-js/website#35]
In the documentation for [conditional attributes](https://markojs.com/docs/syntax/#conditional-attributes), it says:

> If an attribute value expression evaluates to `null` or `false` then the attribute is not included in the output.

The attribute is also omitted when the value is `undefined`. That should be listed. Happy to do a PR unless there's a reason not to document this behavior.

I verified this experimentally (first question I had when I read that bit of the doc) and by looking at the code. It's implemented by `marko/src/runtime/html/helper-attr.js` at what is currently lines [22 & 23](https://github.com/marko-js/marko/blob/0f5e639775cb23a75fea5669e4a651ded537f6f7/src/runtime/html/helper-attr.js#L22):

>         } else if (value == null || value === false) {
>             return "";

and similarly in `/src/runtime/vdom/VElement.js` currently on [line 406](https://github.com/marko-js/marko/blob/0f5e639775cb23a75fea5669e4a651ded537f6f7/src/runtime/vdom/VElement.js#L406) (currently), which also has this helpful comment a bit before it calling out the intent:

>         // Loop over all of the attributes in the attribute map and compare
>         // them to the value in the old map. However, if the value is
>         // null/undefined/false then we want to remove the attribute

**Comment by tigt** [comment]
It looks like this was implemented, as [the docs now mention `undefined`](https://github.com/marko-js/marko/blob/master/docs/syntax.md#boolean-attributes). Okay to close?

**Comment by tjcrowder** [comment]
@tigt  - Looks good!
