### ISSUE TITLE
Try online: whitespace lacks text for textarea

### ISSUE THREAD

**Issue by tigt** [marko-js/website#40]
Moved from marko-js/marko#1390 because this seems to be a site-specific bug, not with marko the library proper.

### Marko Version: 4.18.5

Opening Firefox’s Debugger devtools tab has multiple instances of `marko$4.18.5`, which seems like a safe bet.

### Details

The sample template is:

```marko
<pre>
  By default, pre tags have
  their whitespace preserved
</pre>
<textarea>
  Same for
  text areas!
</textarea>
```

### Expected Behavior

I would assume this template to transform into basically its source code.

### Actual Behavior

```html
<pre>
  By default, pre tags have
  their whitespace preserved
</pre>
<textarea></textarea>
```

### Your Environment

- Firefox 70.0a1
- MacOS

### Steps to Reproduce

Visit https://markojs.com/try-online/?file=%2Fmarko-language-guide%2Fcomponents%2Fwhitespace&gist=

**Comment by DylanPiercey** [comment]
Looks to be fixed now https://markojs.com/try-online/?file=%2Fcomponents%2Fwhitespace%2Findex.marko
