### ISSUE TITLE
Trouble getting website to run

### ISSUE THREAD

**Issue by limitlessloop** [marko-js/website#42]
I downloaded the repo and encountered some issues trying to get it to run. I managed to get it running so the below might help someone else.

I updated all the dependencies, but it was struggling with the following block of code

```js
highlighter.requireGrammarsSync({
  modulePath: require.resolve("language-html/package.json")
});
```

The terminal said

```bash
Error: Cannot find module 'language-html/package.json'
```

When I tried to manually install the above using `npm install language-html/package.json` I got a bit console output with errors.

```bash
...
13 warnings and 17 errors generated.
make: *** [Release/obj.target/tree_sitter_embedded_template_binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/limitlessloop/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
```
I found an article about debugging issues with __make failed with exit code: 2__.

https://codeforgeek.com/make-failed-with-exit-code-2/

I followed each step up until step 3, with no luck. Then I tried updating NVM follow the advice on the NVM github repo.

Suddenly it works. I'm not really sure what step in particular fixed the issue but there may be something in here that's useful for others.

**Comment by tigt** [comment]
After trying to do what you did for about an hour, maybe the best thing is to switch the syntax highlighting for HTML to another package that doesn’t need `node-gyp`.

**Comment by DylanPiercey** [comment]
The website has transitioned to `@marko/serve` and `@marko/build` and a much simpler setup. This issue should be resolved now!
