### ISSUE TITLE
"$" is not rendered properly in some parts of the docs

### ISSUE THREAD

**Issue by achou11** [marko-js/website#53]
There are several places where `$` in the docs renders the HTML entity instead i.e. `&#36;`. An exhaustive list of where this occurs:

- Gudes
  - [Styles](https://markojs.com/docs/styles/)
  - [Body content](https://markojs.com/docs/body-content/)
  - [Color picker](https://markojs.com/docs/color-picker/)
  - [Marko 4 upgrade](https://markojs.com/docs/marko-4-upgrade/)
- Reference
  - [Rendering](https://markojs.com/docs/rendering/)
  - [Syntax](https://markojs.com/docs/syntax/)
  - [Core Tags](https://markojs.com/docs/core-tags/)
  - [Class components](https://markojs.com/docs/class-components/)
- Bundler Integrations
  - [Lasso](https://markojs.com/docs/lasso/)
- Articles
  - [Marko vs. React](https://markojs.com/docs/marko-vs-react/)
  - [10 Awesome Marko features](https://markojs.com/docs/10-awesome-marko-features/)

If you view source for any of these instances, you'll notice that the raw values are `&amp;#36;` when they should just be `&#36;`. Possibly something that needs to be adjusted in the [`markodown-loader`](https://github.com/marko-js/website/blob/b4f63b649e4a18f6ca769a6cbf071845607a9b5e/src/utils/markodown-loader.js)?

**Comment by DylanPiercey** [comment]
@achou11 thanks for creating the details issue. I believe this should be fixed now. 😄
